[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gameya_fi_rust = "534KaupWbMj7brydEXfZVGsYoSiDCwxQEbJCyQsrMoLN"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
